module.exports = {
  projects: [
    '<rootDir>/libs/angular/core',
    '<rootDir>/apps/angular/app',
    '<rootDir>/libs/data/system',
    '<rootDir>/libs/meta/generated',
    '<rootDir>/libs/domain/generated',
    '<rootDir>/libs/domain/system',
    '<rootDir>/libs/meta/system',
    '<rootDir>/libs/protocol/system',
    '<rootDir>/libs/domain/custom',
    '<rootDir>/libs/meta/core',
    '<rootDir>/libs/meta/custom',
    '<rootDir>/libs/angular/material/core',
    '<rootDir>/apps/angular/material/app',
    '<rootDir>/libs/angular/material/custom',
    '<rootDir>/libs/promise/core',
    '<rootDir>/libs/promise/custom',
    '<rootDir>/apps/gatsby',
    '<rootDir>/libs/gatsby/source/core',
    '<rootDir>/libs/gatsby/source/custom',
    '<rootDir>/libs/angular/custom',
    '<rootDir>/libs/angular/services/core',
    '<rootDir>/libs/angular/material/services/core',
  ],
};
