import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { MetaDomain, Good, ProductQuote, QuoteItem, RequestItem, SerialisedInventoryItem, InventoryItem, NonSerialisedInventoryItem, UnitOfMeasure, Product } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class QuoteItemEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    quote: ProductQuote;
    quoteItem: QuoteItem;
    requestItem: RequestItem;
    inventoryItems: InventoryItem[];
    serialisedInventoryItem: SerialisedInventoryItem;
    nonSerialisedInventoryItem: NonSerialisedInventoryItem;
    goods: Good[];
    unitsOfMeasure: UnitOfMeasure[];
    goodsFilter: Filter;
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    goodSelected(product: Product): void;
    submit(): void;
    cancel(): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
