import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { TdMediaService } from "@covalent/core";
import { MetaDomain, Singleton, WorkEffortAssignment, WorkEffortState, Priority, Person, WorkTask, WorkEffortPurpose } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class WorkTaskEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private route;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    subTitle: string;
    m: MetaDomain;
    workTask: WorkTask;
    workEffortStates: WorkEffortState[];
    priorities: Priority[];
    workEffortPurposes: WorkEffortPurpose[];
    singleton: Singleton;
    employees: Person[];
    workEffortAssignments: WorkEffortAssignment[];
    assignees: Person[];
    existingAssignees: Person[];
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, route: ActivatedRoute, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    save(): void;
    goBack(): void;
}
