import { AfterViewInit, ChangeDetectorRef, OnDestroy } from "@angular/core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { MatDialog, MatSnackBar } from "@angular/material";
import { Title } from "@angular/platform-browser";
import { Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { Brand, Good, InventoryItemKind, Model, Organisation, Ownership, ProductCategory, ProductType, SerialisedInventoryItemState } from "@allors/workspace";
import { ErrorService, WorkspaceService } from "@allors/base-angular";
export declare class GoodsOverviewComponent implements AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private formBuilder;
    private titleService;
    private dialog;
    private snackBar;
    private router;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    total: number;
    searchForm: FormGroup;
    data: Good[];
    filtered: Good[];
    chosenGood: string;
    productCategories: ProductCategory[];
    selectedProductCategory: ProductCategory;
    productCategory: ProductCategory;
    productTypes: ProductType[];
    selectedProductType: ProductType;
    productType: ProductType;
    brands: Brand[];
    selectedBrand: Brand;
    brand: Brand;
    models: Model[];
    selectedModel: Model;
    model: Model;
    objectStates: SerialisedInventoryItemState[];
    selectedObjectState: Model;
    objectState: Model;
    ownerships: Ownership[];
    selectedOwnership: Ownership;
    ownership: Ownership;
    inventoryItemKinds: InventoryItemKind[];
    selectedInventoryItemKind: InventoryItemKind;
    inventoryItemKind: InventoryItemKind;
    suppliers: Organisation[];
    selectedSupplier: Organisation;
    supplier: Organisation;
    manufacturers: Organisation[];
    selectedManufacturer: Organisation;
    manufacturer: Organisation;
    private refresh$;
    private page$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, formBuilder: FormBuilder, titleService: Title, dialog: MatDialog, snackBar: MatSnackBar, router: Router, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    more(): void;
    delete(good: Good): void;
    addGood(): void;
    serialisedGood(good: Good): boolean;
    goBack(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onView(good: Good): void;
}
