trigger:
- master

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
    adapters_memory:
      target: 'AdaptersTestMemory'
    adapters_sqlclient:
      target: 'AdaptersTestSqlClient'
    adapters_npgsql:
      target: 'AdaptersTestNpgsql'
  maxParallel: 10
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-target ' + $(target)
    failOnStderr: true
  displayName: $(target)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: 'artifacts/tests'
  displayName: 'Publish Test results'
