trigger:
- master

stages:
- stage: Test
  jobs:  
  - job: Test
    timeoutInMinutes: 120

    pool:
      vmImage: 'windows-2019'
    
    strategy:
      matrix:
        adapters_memory:
          target: '-target AdaptersTestMemory'
        adapters_sqlclient:
          target: '-target AdaptersTestSqlClient'
        adapters_npgsql:
          target: '-target AdaptersTestNpgsql'
        base_database:
          target: '-target BaseDatabaseTest'
        base_workspace:
          target: '-target BaseWorkspaceTest'
        apps_database:
          target: '-target AppsDatabaseTest'
        apps_workspace:
          target: '-target AppsWorkspaceTest'
      maxParallel: 10
    
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: $(target)
        failOnStderr: true
      displayName: $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Publish Test results'