trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-configuration $(buildConfiguration) -target Adapters'
    failOnStderr: true
  displayName: 'Build & Test Adapters'
- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: 'artifacts/tests'
   displayName: 'Publish Test results'
