classDiagram
	class Auditable {
		<<interface>>
		User CreatedBy
		User LastModifiedBy
		DateTime CreationDate
		DateTime LastModifiedDate
	}
	class Cachable {
		<<interface>>
		Guid CacheId
	}
	class Deletable {
		<<interface>>
	}
	class Enumeration {
		<<interface>>
		string Name
		LocalisedText[] LocalisedNames
		bool IsActive
	}
	class Object {
		<<interface>>
		Permission[] DeniedPermissions
		SecurityToken[] SecurityTokens
	}
	class UniquelyIdentifiable {
		<<interface>>
		Guid UniqueId
	}
	class Version {
		<<interface>>
		Guid DerivationId
		DateTime DerivationTimeStamp
	}
	class Versioned {
		<<interface>>
	}
	class Printable {
		<<interface>>
		PrintDocument PrintDocument
	}
	class Localised {
		<<interface>>
		Locale Locale
	}
	class DelegatedAccessControlledObject {
		<<interface>>
	}
	class SecurityTokenOwner {
		<<interface>>
		SecurityToken _OwnerSecurityToken
		AccessControl _OwnerAccessControl
	}
	class ApproveTask {
		<<interface>>
		string Comment
		Notification _RejectionNotification
		Notification _ApprovalNotification
	}
	class ObjectState {
		<<interface>>
		Permission[] ObjectDeniedPermissions
		string Name
	}
	class Task {
		<<interface>>
		WorkItem _WorkItem
		string _Title
		DateTime _DateCreated
		DateTime _DateDue
		DateTime DateClosed
		User[] _Participants
		User _Performer
	}
	class Transitional {
		<<interface>>
		ObjectState[] _PreviousObjectStates
		ObjectState[] _LastObjectStates
		ObjectState[] _ObjectStates
	}
	class TransitionalVersion {
		<<interface>>
		ObjectState[] __PreviousObjectStates
		ObjectState[] __LastObjectStates
		ObjectState[] __ObjectStates
	}
	class User {
		<<interface>>
		string UserName
		string _NormalizedUserName
		string InUserPassword
		string UserPasswordHash
		string UserEmail
		string _NormalizedUserEmail
		bool UserEmailConfirmed
		string UserSecurityStamp
		string UserPhoneNumber
		bool UserPhoneNumberConfirmed
		bool UserTwoFactorEnabled
		DateTime UserLockoutEnd
		bool UserLockoutEnabled
		int UserAccessFailedCount
		IdentityClaim[] IdentityClaims
		Login[] Logins
		NotificationList NotificationList
	}
	class WorkItem {
		<<interface>>
		string _WorkItemDescription
	}
	class AccessInterface {
		<<interface>>
	}
	class Address {
		<<interface>>
		Place Place
	}
	class Addressable {
		<<interface>>
		Address _Address
	}
	class DerivationCounted {
		<<interface>>
		int DerivationCount
	}
	class I1 {
		<<interface>>
		I1 I1I1Many2One
		I12[] I1I12Many2Manies
		I2[] I1I2Many2Manies
		I2 I1I2Many2One
		string I1AllorsString
		I12 I1I12Many2One
		DateTime I1AllorsDateTime
		I2[] I1I2One2Manies
		C2[] I1C2One2Manies
		C1 I1C1One2One
		int I1AllorsInteger
		C2[] I1C2Many2Manies
		I1[] I1I1One2Manies
		I1[] I1I1Many2Manies
		bool I1AllorsBoolean
		decimal I1AllorsDecimal
		I12 I1I12One2One
		I2 I1I2One2One
		C2 I1C2One2One
		C1[] I1C1One2Manies
		byte[] I1AllorsBinary
		C1[] I1C1Many2Manies
		double I1AllorsDouble
		I1 I1I1One2One
		C1 I1C1Many2One
		I12[] I1I12One2Manies
		C2 I1C2Many2One
		Guid I1AllorsUnique
	}
	class I12 {
		<<interface>>
		byte[] I12AllorsBinary
		C2 I12C2One2One
		double I12AllorsDouble
		I1 I12I1Many2One
		string I12AllorsString
		I12[] I12I12Many2Manies
		decimal I12AllorsDecimal
		I2[] I12I2Many2Manies
		C2[] I12C2Many2Manies
		I1[] I12I1Many2Manies
		I12[] I12I12One2Manies
		string Name
		C1[] I12C1Many2Manies
		I2 I12I2Many2One
		Guid I12AllorsUnique
		int I12AllorsInteger
		I1[] I12I1One2Manies
		C1 I12C1One2One
		I12 I12I12One2One
		I2 I12I2One2One
		I12[] Dependencies
		I2[] I12I2One2Manies
		C2 I12C2Many2One
		I12 I12I12Many2One
		bool I12AllorsBoolean
		I1 I12I1One2One
		C1[] I12C1One2Manies
		C1 I12C1Many2One
		DateTime I12AllorsDateTime
	}
	class I2 {
		<<interface>>
		I2 I2I2Many2One
		C1 I2C1Many2One
		I12 I2I12Many2One
		bool I2AllorsBoolean
		C1[] I2C1One2Manies
		C1 I2C1One2One
		decimal I2AllorsDecimal
		I2[] I2I2Many2Manies
		byte[] I2AllorsBinary
		Guid I2AllorsUnique
		I1 I2I1Many2One
		DateTime I2AllorsDateTime
		I12[] I2I12One2Manies
		I12 I2I12One2One
		C2[] I2C2Many2Manies
		I1[] I2I1Many2Manies
		C2 I2C2Many2One
		string I2AllorsString
		C2[] I2C2One2Manies
		I1 I2I1One2One
		I1[] I2I1One2Manies
		I12[] I2I12Many2Manies
		I2 I2I2One2One
		int I2AllorsInteger
		I2[] I2I2One2Manies
		C1[] I2C1Many2Manies
		C2 I2C2One2One
		double I2AllorsDouble
	}
	class S1 {
		<<interface>>
	}
	class Shared {
		<<interface>>
	}
	class SyncDepthI1 {
		<<interface>>
		SyncDepth2 __SyncDepth2
		int Value
	}
	class ValidationI12 {
		<<interface>>
		Guid UniqueId
	}
	class Counter {
		int Value
	}
	class Singleton {
		Locale DefaultLocale
		Locale[] AdditionalLocales
		Locale[] _Locales
		Media LogoImage
		Person AutocompleteDefault
		Person SelectDefault
	}
	class Media {
		Guid _Revision
		MediaContent MediaContent
		string InType
		byte[] InData
		string InDataUri
		string InFileName
		string Name
		string _Type
		string _FileName
	}
	class MediaContent {
		string Type
		byte[] Data
	}
	class PrintDocument {
		Media Media
	}
	class Template {
		TemplateType TemplateType
		Media Media
		string Arguments
	}
	class TemplateType {
	}
	class PreparedExtent {
		string Name
		string Description
		string Content
	}
	class PreparedFetch {
		string Name
		string Description
		string Content
	}
	class Country {
		Currency Currency
		string IsoCode
		string Name
		LocalisedText[] LocalisedNames
	}
	class Currency {
		string IsoCode
	}
	class Language {
		string IsoCode
		string Name
		LocalisedText[] LocalisedNames
		string NativeName
	}
	class Locale {
		string Name
		Language Language
		Country Country
	}
	class LocalisedMedia {
		Media Media
	}
	class LocalisedText {
		string Text
	}
	class AccessControl {
		UserGroup[] SubjectGroups
		User[] Subjects
		Role Role
		Permission[] _EffectivePermissions
		string _EffectiveWorkspacePermissionIds
		User[] _EffectiveUsers
	}
	class IdentityClaim {
		string Type
		string Value
		string ValueType
		string Issuer
		string OriginalIssuer
	}
	class Login {
		string Key
		string Provider
		string DisplayName
	}
	class Permission {
		Guid OperandTypePointer
		Guid ConcreteClassPointer
		int OperationEnum
	}
	class Role {
		Permission[] Permissions
		string Name
	}
	class SecurityToken {
		AccessControl[] AccessControls
	}
	class AutomatedAgent {
		string Name
		string Description
	}
	class EmailMessage {
		DateTime _DateCreated
		DateTime DateSending
		DateTime DateSent
		User Sender
		User[] Recipients
		string RecipientEmailAddress
		string Subject
		string Body
	}
	class Notification {
		UniquelyIdentifiable Target
		bool Confirmed
		string Title
		string Description
		DateTime _DateCreated
	}
	class NotificationList {
		Notification[] Notifications
		Notification[] _UnconfirmedNotifications
		Notification[] _ConfirmedNotifications
	}
	class Person {
		string FirstName
		string MiddleName
		string LastName
		Address[] Addresses
		int Age
		DateTime BirthDate
		string _FullName
		Gender Gender
		bool IsMarried
		bool IsStudent
		MailboxAddress MailboxAddress
		Address MainAddress
		Media Photo
		Media[] Pictures
		int ShirtSize
		string Text
		string TinyMCEText
		decimal Weight
		Organisation CycleOne
		Organisation[] CycleMany
		string WorkspaceField
		string DatabaseOnlyField
	}
	class TaskAssignment {
		User User
		Notification Notification
		Task Task
	}
	class UserGroup {
		User[] Members
		string Name
	}
	class AccessClass {
		bool Block
		string Property
	}
	class BadUI {
		Person[] PersonsMany
		Organisation CompanyOne
		Person PersonOne
		Organisation CompanyMany
		string AllorsString
	}
	class Build {
		Guid Guid
		string String
	}
	class C1 {
		byte[] C1AllorsBinary
		bool C1AllorsBoolean
		DateTime C1AllorsDateTime
		decimal C1AllorsDecimal
		double C1AllorsDouble
		int C1AllorsInteger
		string C1AllorsString
		string AllorsStringMax
		Guid C1AllorsUnique
		C1[] C1C1Many2Manies
		C1 C1C1Many2One
		C1[] C1C1One2Manies
		C1 C1C1One2One
		C2[] C1C2Many2Manies
		C2 C1C2Many2One
		C2[] C1C2One2Manies
		C2 C1C2One2One
		I12[] C1I12Many2Manies
		I12 C1I12Many2One
		I12[] C1I12One2Manies
		I12 C1I12One2One
		I1[] C1I1Many2Manies
		I1 C1I1Many2One
		I1[] C1I1One2Manies
		I1 C1I1One2One
		I2[] C1I2Many2Manies
		I2 C1I2Many2One
		I2[] C1I2One2Manies
		I2 C1I2One2One
	}
	class C2 {
		decimal C2AllorsDecimal
		C1 C2C1One2One
		C2 C2C2Many2One
		Guid C2AllorsUnique
		I12 C2I12Many2One
		I12 C2I12One2One
		I1[] C2I1Many2Manies
		double C2AllorsDouble
		I1[] C2I1One2Manies
		I2 C2I2One2One
		int C2AllorsInteger
		I2[] C2I2Many2Manies
		I12[] C2I12Many2Manies
		C2[] C2C2One2Manies
		bool C2AllorsBoolean
		I1 C2I1Many2One
		I1 C2I1One2One
		C1[] C2C1Many2Manies
		I12[] C2I12One2Manies
		I2[] C2I2One2Manies
		C2 C2C2One2One
		string C2AllorsString
		C1 C2C1Many2One
		C2[] C2C2Many2Manies
		DateTime C2AllorsDateTime
		I2 C2I2Many2One
		C1[] C2C1One2Manies
		byte[] C2AllorsBinary
		S1 S1One2One
	}
	class ClassWithoutRoles {
	}
	class Data {
		Person AutocompleteFilter
		Person AutocompleteOptions
		Person AutocompleteAssignedFilter
		Person AutocompleteDerivedFilter
		Person AutocompleteAssignedOptions
		Person AutocompleteDerivedOptions
		bool Checkbox
		Person[] Chips
		string String
		decimal Decimal
		DateTime Date
		DateTime DateTime
		DateTime DateTime2
		Media File
		Media[] MultipleFiles
		string RadioGroup
		Person Select
		Person SelectAssigned
		Person SelectDerived
		int Slider
		bool SlideToggle
		string PlainText
		string Markdown
		string Html
		LocalisedText[] LocalisedTexts
		LocalisedText[] LocalisedMarkdowns
	}
	class Dependee {
		Subdependee Subdependee
		int Subcounter
		int Counter
		bool DeleteDependent
	}
	class Dependent {
		Dependee Dependee
		int Counter
		int Subcounter
	}
	class Extender {
		string AllorsString
	}
	class First {
		Second Second
		bool CreateCycle
		bool IsDerived
	}
	class Four {
	}
	class From {
		To[] Tos
	}
	class Gender {
	}
	class HomeAddress {
		string Street
		string HouseNumber
	}
	class Left {
		Middle Middle
		int Counter
		bool CreateMiddle
	}
	class MailboxAddress {
		string PoBox
	}
	class MediaTyped {
		string Markdown
	}
	class Middle {
		Right Right
		int Counter
	}
	class One {
		Two Two
	}
	class Order {
		OrderState _PreviousOrderState
		OrderState _LastOrderState
		OrderState OrderState
		ShipmentState _PreviousShipmentState
		ShipmentState _LastShipmentState
		ShipmentState ShipmentState
		PaymentState _PreviousPaymentState
		PaymentState _LastPaymentState
		PaymentState PaymentState
		OrderLine[] OrderLines
		decimal Amount
		OrderState NonVersionedCurrentObjectState
		OrderLine[] NonVersionedOrderLines
		decimal NonVersionedAmount
		OrderVersion CurrentVersion
		OrderVersion[] AllVersions
	}
	class OrderLine {
		decimal Amount
		OrderLineVersion CurrentVersion
		OrderLineVersion[] AllVersions
	}
	class OrderLineVersion {
		decimal Amount
	}
	class OrderState {
	}
	class OrderVersion {
		OrderState OrderState
		OrderLine[] OrderLines
		decimal _Amount
	}
	class Organisation {
		Address[] Addresses
		string Description
		Person[] Employees
		Media[] Images
		bool IsCustomer
		bool Incorporated
		DateTime IncorporationDate
		string Information
		bool IsSupplier
		Media Logo
		Address MainAddress
		Person Manager
		string Name
		Person Owner
		Person[] Shareholders
		string Size
		Person CycleOne
		Person[] CycleMany
		Data OneData
		Data[] ManyDatas
		bool JustDidIt
	}
	class Page {
		string Name
		Media Content
	}
	class PaymentState {
	}
	class Place {
		Country Country
		string City
		string PostalCode
	}
	class Post {
		int Counter
	}
	class Right {
		int Counter
	}
	class Second {
		Third Third
		bool IsDerived
	}
	class ShipmentState {
	}
	class SimpleJob {
		int Index
	}
	class StatefulCompany {
		Person Employee
		string Name
		Person Manager
	}
	class Subdependee {
		int Subcounter
	}
	class SyncDepth2 {
		int Value
	}
	class SyncDepthC1 {
	}
	class SyncRoot {
		SyncDepthI1 __SyncDepth1
		int Value
	}
	class Tagged {
		bool SingleTag
		bool MultipleTags
	}
	class Third {
		bool IsDerived
	}
	class Three {
		Four Four
		string AllorsString
	}
	class To {
		string Name
	}
	class Two {
		Shared Shared
	}
	class UnitSample {
		byte[] AllorsBinary
		DateTime AllorsDateTime
		bool AllorsBoolean
		double AllorsDouble
		int AllorsInteger
		string AllorsString
		Guid AllorsUnique
		decimal AllorsDecimal
		byte[] RequiredBinary
		DateTime RequiredDateTime
		bool RequiredBoolean
		double RequiredDouble
		int RequiredInteger
		string RequiredString
		Guid RequiredUnique
		decimal RequiredDecimal
	}
	class ValidationC1 {
	}
	class ValidationC2 {
	}

Object <|-- Auditable
Object <|-- Cachable
Object <|-- Deletable
UniquelyIdentifiable <|-- Enumeration
Object <|-- UniquelyIdentifiable
Object <|-- Version
Object <|-- Versioned
Object <|-- Printable
Object <|-- Localised
Object <|-- DelegatedAccessControlledObject
Object <|-- SecurityTokenOwner
Task <|-- ApproveTask
UniquelyIdentifiable <|-- ObjectState
UniquelyIdentifiable <|-- Task
Deletable <|-- Task
Object <|-- Transitional
Object <|-- TransitionalVersion
UniquelyIdentifiable <|-- User
SecurityTokenOwner <|-- User
Object <|-- WorkItem
DelegatedAccessControlledObject <|-- AccessInterface
Object <|-- Address
Object <|-- Addressable
Object <|-- DerivationCounted
I12 <|-- I1
S1 <|-- I1
Object <|-- I12
I12 <|-- I2
Object <|-- S1
Object <|-- Shared
DerivationCounted <|-- SyncDepthI1
Object <|-- ValidationI12
UniquelyIdentifiable <|-- Counter
Object <|-- Singleton
UniquelyIdentifiable <|-- Media
Deletable <|-- Media
Deletable <|-- MediaContent
Deletable <|-- PrintDocument
UniquelyIdentifiable <|-- Template
Deletable <|-- Template
Enumeration <|-- TemplateType
Deletable <|-- TemplateType
UniquelyIdentifiable <|-- PreparedExtent
Deletable <|-- PreparedExtent
UniquelyIdentifiable <|-- PreparedFetch
Deletable <|-- PreparedFetch
Object <|-- Country
Enumeration <|-- Currency
Object <|-- Language
Object <|-- Locale
Localised <|-- LocalisedMedia
Deletable <|-- LocalisedMedia
Localised <|-- LocalisedText
Deletable <|-- LocalisedText
UniquelyIdentifiable <|-- AccessControl
Cachable <|-- AccessControl
Deletable <|-- AccessControl
Deletable <|-- IdentityClaim
Deletable <|-- Login
Deletable <|-- Permission
UniquelyIdentifiable <|-- Role
UniquelyIdentifiable <|-- SecurityToken
Deletable <|-- SecurityToken
User <|-- AutomatedAgent
Object <|-- EmailMessage
Deletable <|-- Notification
Deletable <|-- NotificationList
User <|-- Person
Addressable <|-- Person
Deletable <|-- Person
Deletable <|-- TaskAssignment
UniquelyIdentifiable <|-- UserGroup
AccessInterface <|-- AccessClass
Object <|-- BadUI
Object <|-- Build
I1 <|-- C1
DerivationCounted <|-- C1
DerivationCounted <|-- C2
I2 <|-- C2
Object <|-- ClassWithoutRoles
Object <|-- Data
DerivationCounted <|-- Dependee
Deletable <|-- Dependent
DerivationCounted <|-- Dependent
Object <|-- Extender
DerivationCounted <|-- First
Shared <|-- Four
Object <|-- From
Enumeration <|-- Gender
Address <|-- HomeAddress
DerivationCounted <|-- Left
Address <|-- MailboxAddress
Object <|-- MediaTyped
DerivationCounted <|-- Middle
Shared <|-- One
Transitional <|-- Order
Versioned <|-- Order
Versioned <|-- OrderLine
Version <|-- OrderLineVersion
ObjectState <|-- OrderState
Version <|-- OrderVersion
Addressable <|-- Organisation
Deletable <|-- Organisation
UniquelyIdentifiable <|-- Organisation
UniquelyIdentifiable <|-- Page
ObjectState <|-- PaymentState
Object <|-- Place
Object <|-- Post
DerivationCounted <|-- Right
DerivationCounted <|-- Second
ObjectState <|-- ShipmentState
Object <|-- SimpleJob
Object <|-- StatefulCompany
Object <|-- Subdependee
DerivationCounted <|-- SyncDepth2
SyncDepthI1 <|-- SyncDepthC1
DerivationCounted <|-- SyncRoot
Object <|-- Tagged
DerivationCounted <|-- Third
Shared <|-- Three
Object <|-- To
Shared <|-- Two
Object <|-- UnitSample
ValidationI12 <|-- ValidationC1
ValidationI12 <|-- ValidationC2
