import { AfterViewInit, ChangeDetectorRef, OnDestroy } from "@angular/core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { MatSnackBar } from "@angular/material";
import { Title } from "@angular/platform-browser";
import { Router } from "@angular/router";
import 'rxjs/add/observable/combineLatest';
import { TdDialogService, TdMediaService } from "@covalent/core";
import { Organisation, Country, OrganisationRole, CustomOrganisationClassification } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class OrganisationsOverviewComponent implements AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private formBuilder;
    private titleService;
    private snackBar;
    private router;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    total: number;
    searchForm: FormGroup;
    data: Organisation[];
    countries: Country[];
    selectedCountry: Country;
    country: Country;
    roles: OrganisationRole[];
    selectedRole: OrganisationRole;
    role: OrganisationRole;
    classifications: CustomOrganisationClassification[];
    selectedClassification: CustomOrganisationClassification;
    classification: CustomOrganisationClassification;
    private refresh$;
    private subscription;
    private scope;
    private page$;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, formBuilder: FormBuilder, titleService: Title, snackBar: MatSnackBar, router: Router, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    more(): void;
    goBack(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    refresh(): void;
    delete(organisation: Organisation): void;
    onView(organisation: Organisation): void;
}
