import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { MetaDomain, PartyContactMechanism, Person, CommunicationEvent, Organisation, OrganisationContactRelationship, ContactMechanism } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class OrganisationOverviewComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private route;
    private dialogService;
    private snackBar;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    organisation: Organisation;
    communicationEvents: CommunicationEvent[];
    contactsCollection: string;
    currentContactRelationships: OrganisationContactRelationship[];
    inactiveContactRelationships: OrganisationContactRelationship[];
    allContactRelationships: OrganisationContactRelationship[];
    contactMechanismsCollection: string;
    currentContactMechanisms: PartyContactMechanism[];
    inactiveContactMechanisms: PartyContactMechanism[];
    allContactMechanisms: PartyContactMechanism[];
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, route: ActivatedRoute, dialogService: TdDialogService, snackBar: MatSnackBar, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    readonly contactRelationships: any;
    readonly contactMechanisms: any;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    removeContact(organisationContactRelationship: OrganisationContactRelationship): void;
    activateContact(organisationContactRelationship: OrganisationContactRelationship): void;
    deleteContact(person: Person): void;
    removeContactMechanism(partyContactMechanism: PartyContactMechanism): void;
    activateContactMechanism(partyContactMechanism: PartyContactMechanism): void;
    deleteContactMechanism(contactMechanism: ContactMechanism): void;
    cancelCommunication(communicationEvent: CommunicationEvent): void;
    closeCommunication(communicationEvent: CommunicationEvent): void;
    reopenCommunication(communicationEvent: CommunicationEvent): void;
    deleteCommunication(communicationEvent: CommunicationEvent): void;
    goBack(): void;
    refresh(): void;
    isPhone(contactMechanism: ContactMechanism): boolean;
    checkType(obj: any): string;
}
