import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { ActivatedRoute } from "@angular/router";
import { TdMediaService } from "@covalent/core";
import 'rxjs/add/observable/combineLatest';
import { MetaDomain, Enumeration, Person, OrganisationContactRelationship, PersonRole } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class OrganisationContactrelationshipAddComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private route;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    subTitle: string;
    m: MetaDomain;
    peopleFilter: Filter;
    organisationContactRelationship: OrganisationContactRelationship;
    person: Person;
    organisationContactKinds: Enumeration[];
    roles: PersonRole[];
    addPerson: boolean;
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, route: ActivatedRoute, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    personCancelled(): void;
    personAdded(id: string): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
