// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Currencies.cs" company="Allors bvba">
//   Copyright 2002-2016 Allors bvba.
//
// Dual Licensed under
//   a) the General Public Licence v3 (GPL)
//   b) the Allors License
//
// The GPL License is included in the file gpl.txt.
// The Allors License is an addendum to your contract.
//
// Allors Applications is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// For more information visit http://www.allors.com/legal
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
namespace Allors.Domain
{
    public partial class Currencies
    {
        private Cache<string, Currency> currencyByCode;

        public Cache<string, Currency> CurrencyByCode => this.currencyByCode ?? (this.currencyByCode = new Cache<string, Currency>(this.Session, this.Meta.IsoCode));

        protected override void BaseSetup(Setup config)
        {
            var data = new[,]
            {
                {
                  "Afghani",
                  "AFN",
                  "971",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Lek",
                  "ALL",
                  "008",
                  "2",
                },
                {
                  "Algerian Dinar",
                  "DZD",
                  "012",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Kwanza",
                  "AOA",
                  "973",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Argentine Peso",
                  "ARS",
                  "032",
                  "2",
                },
                {
                  "Armenian Dram",
                  "AMD",
                  "051",
                  "2",
                },
                {
                  "Aruban Florin",
                  "AWG",
                  "533",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Azerbaijanian Manat",
                  "AZN",
                  "944",
                  "2",
                },
                {
                  "Bahamian Dollar",
                  "BSD",
                  "044",
                  "2",
                },
                {
                  "Bahraini Dinar",
                  "BHD",
                  "048",
                  "3",
                },
                {
                  "Taka",
                  "BDT",
                  "050",
                  "2",
                },
                {
                  "Barbados Dollar",
                  "BBD",
                  "052",
                  "2",
                },
                {
                  "Belarusian Ruble",
                  "BYN",
                  "933",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Belize Dollar",
                  "BZD",
                  "084",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Bermudian Dollar",
                  "BMD",
                  "060",
                  "2",
                },
                {
                  "Indian Rupee",
                  "INR",
                  "356",
                  "2",
                },
                {
                  "Ngultrum",
                  "BTN",
                  "064",
                  "2",
                },
                {
                  "Boliviano",
                  "BOB",
                  "068",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Convertible Mark",
                  "BAM",
                  "977",
                  "2",
                },
                {
                  "Pula",
                  "BWP",
                  "072",
                  "2",
                },
                {
                  "Norwegian Krone",
                  "NOK",
                  "578",
                  "2",
                },
                {
                  "Brazilian Real",
                  "BRL",
                  "986",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Brunei Dollar",
                  "BND",
                  "096",
                  "2",
                },
                {
                  "Bulgarian Lev",
                  "BGN",
                  "975",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Burundi Franc",
                  "BIF",
                  "108",
                  "0",
                },
                {
                  "Cabo Verde Escudo",
                  "CVE",
                  "132",
                  "2",
                },
                {
                  "Riel",
                  "KHR",
                  "116",
                  "2",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "Canadian Dollar",
                  "CAD",
                  "124",
                  "2",
                },
                {
                  "Cayman Islands Dollar",
                  "KYD",
                  "136",
                  "2",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "Chilean Peso",
                  "CLP",
                  "152",
                  "0",
                },
                {
                  "Yuan Renminbi",
                  "CNY",
                  "156",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Colombian Peso",
                  "COP",
                  "170",
                  "2",
                },
                {
                  "Comoro Franc",
                  "KMF",
                  "174",
                  "0",
                },
                {
                  "Congolese Franc",
                  "CDF",
                  "976",
                  "2",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "New Zealand Dollar",
                  "NZD",
                  "554",
                  "2",
                },
                {
                  "Costa Rican Colon",
                  "CRC",
                  "188",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Kuna",
                  "HRK",
                  "191",
                  "2",
                },
                {
                  "Cuban Peso",
                  "CUP",
                  "192",
                  "2",
                },
                {
                  "Peso Convertible",
                  "CUC",
                  "931",
                  "2",
                },
                {
                  "Netherlands Antillean Guilder",
                  "ANG",
                  "532",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Czech Koruna",
                  "CZK",
                  "203",
                  "2",
                },
                {
                  "Danish Krone",
                  "DKK",
                  "208",
                  "2",
                },
                {
                  "Djibouti Franc",
                  "DJF",
                  "262",
                  "0",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Dominican Peso",
                  "DOP",
                  "214",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Egyptian Pound",
                  "EGP",
                  "818",
                  "2",
                },
                {
                  "El Salvador Colon",
                  "SVC",
                  "222",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "Nakfa",
                  "ERN",
                  "232",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Ethiopian Birr",
                  "ETB",
                  "230",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Falkland Islands Pound",
                  "FKP",
                  "238",
                  "2",
                },
                {
                  "Danish Krone",
                  "DKK",
                  "208",
                  "2",
                },
                {
                  "Fiji Dollar",
                  "FJD",
                  "242",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "CFP Franc",
                  "XPF",
                  "953",
                  "0",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "CFA Franc BEAC",
                  "XAF",
                  "950",
                  "0",
                },
                {
                  "Dalasi",
                  "GMD",
                  "270",
                  "2",
                },
                {
                  "Lari",
                  "GEL",
                  "981",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Ghana Cedi",
                  "GHS",
                  "936",
                  "2",
                },
                {
                  "Gibraltar Pound",
                  "GIP",
                  "292",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Danish Krone",
                  "DKK",
                  "208",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Quetzal",
                  "GTQ",
                  "320",
                  "2",
                },
                {
                  "Pound Sterling",
                  "GBP",
                  "826",
                  "2",
                },
                {
                  "Guinea Franc",
                  "GNF",
                  "324",
                  "0",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Guyana Dollar",
                  "GYD",
                  "328",
                  "2",
                },
                {
                  "Gourde",
                  "HTG",
                  "332",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Lempira",
                  "HNL",
                  "340",
                  "2",
                },
                {
                  "Hong Kong Dollar",
                  "HKD",
                  "344",
                  "2",
                },
                {
                  "Forint",
                  "HUF",
                  "348",
                  "2",
                },
                {
                  "Iceland Krona",
                  "ISK",
                  "352",
                  "0",
                },
                {
                  "Indian Rupee",
                  "INR",
                  "356",
                  "2",
                },
                {
                  "Rupiah",
                  "IDR",
                  "360",
                  "2",
                },
                {
                  "SDR (Special Drawing Right)",
                  "XDR",
                  "960",
                  "N.A.",
                },
                {
                  "Iranian Rial",
                  "IRR",
                  "364",
                  "2",
                },
                {
                  "Iraqi Dinar",
                  "IQD",
                  "368",
                  "3",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Pound Sterling",
                  "GBP",
                  "826",
                  "2",
                },
                {
                  "New Israeli Sheqel",
                  "ILS",
                  "376",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Jamaican Dollar",
                  "JMD",
                  "388",
                  "2",
                },
                {
                  "Yen",
                  "JPY",
                  "392",
                  "0",
                },
                {
                  "Pound Sterling",
                  "GBP",
                  "826",
                  "2",
                },
                {
                  "Jordanian Dinar",
                  "JOD",
                  "400",
                  "3",
                },
                {
                  "Tenge",
                  "KZT",
                  "398",
                  "2",
                },
                {
                  "Kenyan Shilling",
                  "KES",
                  "404",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "North Korean Won",
                  "KPW",
                  "408",
                  "2",
                },
                {
                  "Won",
                  "KRW",
                  "410",
                  "0",
                },
                {
                  "Kuwaiti Dinar",
                  "KWD",
                  "414",
                  "3",
                },
                {
                  "Som",
                  "KGS",
                  "417",
                  "2",
                },
                {
                  "Kip",
                  "LAK",
                  "418",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Lebanese Pound",
                  "LBP",
                  "422",
                  "2",
                },
                {
                  "Loti",
                  "LSL",
                  "426",
                  "2",
                },
                {
                  "Rand",
                  "ZAR",
                  "710",
                  "2",
                },
                {
                  "Liberian Dollar",
                  "LRD",
                  "430",
                  "2",
                },
                {
                  "Libyan Dinar",
                  "LYD",
                  "434",
                  "3",
                },
                {
                  "Swiss Franc",
                  "CHF",
                  "756",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Pataca",
                  "MOP",
                  "446",
                  "2",
                },
                {
                  "Denar",
                  "MKD",
                  "807",
                  "2",
                },
                {
                  "Malagasy Ariary",
                  "MGA",
                  "969",
                  "2",
                },
                {
                  "Malawi Kwacha",
                  "MWK",
                  "454",
                  "2",
                },
                {
                  "Malaysian Ringgit",
                  "MYR",
                  "458",
                  "2",
                },
                {
                  "Rufiyaa",
                  "MVR",
                  "462",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Ouguiya",
                  "MRO",
                  "478",
                  "2",
                },
                {
                  "Mauritius Rupee",
                  "MUR",
                  "480",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "ADB Unit of Account",
                  "XUA",
                  "965",
                  "N.A.",
                },
                {
                  "Mexican Peso",
                  "MXN",
                  "484",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Moldovan Leu",
                  "MDL",
                  "498",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Tugrik",
                  "MNT",
                  "496",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Moroccan Dirham",
                  "MAD",
                  "504",
                  "2",
                },
                {
                  "Mozambique Metical",
                  "MZN",
                  "943",
                  "2",
                },
                {
                  "Kyat",
                  "MMK",
                  "104",
                  "2",
                },
                {
                  "Namibia Dollar",
                  "NAD",
                  "516",
                  "2",
                },
                {
                  "Rand",
                  "ZAR",
                  "710",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Nepalese Rupee",
                  "NPR",
                  "524",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "CFP Franc",
                  "XPF",
                  "953",
                  "0",
                },
                {
                  "New Zealand Dollar",
                  "NZD",
                  "554",
                  "2",
                },
                {
                  "Cordoba Oro",
                  "NIO",
                  "558",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Naira",
                  "NGN",
                  "566",
                  "2",
                },
                {
                  "New Zealand Dollar",
                  "NZD",
                  "554",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Norwegian Krone",
                  "NOK",
                  "578",
                  "2",
                },
                {
                  "Rial Omani",
                  "OMR",
                  "512",
                  "3",
                },
                {
                  "Pakistan Rupee",
                  "PKR",
                  "586",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Balboa",
                  "PAB",
                  "590",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Kina",
                  "PGK",
                  "598",
                  "2",
                },
                {
                  "Guarani",
                  "PYG",
                  "600",
                  "0",
                },
                {
                  "Sol",
                  "PEN",
                  "604",
                  "2",
                },
                {
                  "Philippine Peso",
                  "PHP",
                  "608",
                  "2",
                },
                {
                  "New Zealand Dollar",
                  "NZD",
                  "554",
                  "2",
                },
                {
                  "Zloty",
                  "PLN",
                  "985",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Qatari Rial",
                  "QAR",
                  "634",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Romanian Leu",
                  "RON",
                  "946",
                  "2",
                },
                {
                  "Russian Ruble",
                  "RUB",
                  "643",
                  "2",
                },
                {
                  "Rwanda Franc",
                  "RWF",
                  "646",
                  "0",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Saint Helena Pound",
                  "SHP",
                  "654",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "East Caribbean Dollar",
                  "XCD",
                  "951",
                  "2",
                },
                {
                  "Tala",
                  "WST",
                  "882",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Dobra",
                  "STD",
                  "678",
                  "2",
                },
                {
                  "Saudi Riyal",
                  "SAR",
                  "682",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "Serbian Dinar",
                  "RSD",
                  "941",
                  "2",
                },
                {
                  "Seychelles Rupee",
                  "SCR",
                  "690",
                  "2",
                },
                {
                  "Leone",
                  "SLL",
                  "694",
                  "2",
                },
                {
                  "Singapore Dollar",
                  "SGD",
                  "702",
                  "2",
                },
                {
                  "Netherlands Antillean Guilder",
                  "ANG",
                  "532",
                  "2",
                },
                {
                  "Sucre",
                  "XSU",
                  "994",
                  "N.A.",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Solomon Islands Dollar",
                  "SBD",
                  "090",
                  "2",
                },
                {
                  "Somali Shilling",
                  "SOS",
                  "706",
                  "2",
                },
                {
                  "Rand",
                  "ZAR",
                  "710",
                  "2",
                },
                {
                  "South Sudanese Pound",
                  "SSP",
                  "728",
                  "2",
                },
                {
                  "Euro",
                  "EUR",
                  "978",
                  "2",
                },
                {
                  "Sri Lanka Rupee",
                  "LKR",
                  "144",
                  "2",
                },
                {
                  "Sudanese Pound",
                  "SDG",
                  "938",
                  "2",
                },
                {
                  "Surinam Dollar",
                  "SRD",
                  "968",
                  "2",
                },
                {
                  "Norwegian Krone",
                  "NOK",
                  "578",
                  "2",
                },
                {
                  "Lilangeni",
                  "SZL",
                  "748",
                  "2",
                },
                {
                  "Swedish Krona",
                  "SEK",
                  "752",
                  "2",
                },
                {
                  "Swiss Franc",
                  "CHF",
                  "756",
                  "2",
                },
                {
                  "Syrian Pound",
                  "SYP",
                  "760",
                  "2",
                },
                {
                  "New Taiwan Dollar",
                  "TWD",
                  "901",
                  "2",
                },
                {
                  "Somoni",
                  "TJS",
                  "972",
                  "2",
                },
                {
                  "Tanzanian Shilling",
                  "TZS",
                  "834",
                  "2",
                },
                {
                  "Baht",
                  "THB",
                  "764",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "CFA Franc BCEAO",
                  "XOF",
                  "952",
                  "0",
                },
                {
                  "New Zealand Dollar",
                  "NZD",
                  "554",
                  "2",
                },
                {
                  "Pa’anga",
                  "TOP",
                  "776",
                  "2",
                },
                {
                  "Trinidad and Tobago Dollar",
                  "TTD",
                  "780",
                  "2",
                },
                {
                  "Tunisian Dinar",
                  "TND",
                  "788",
                  "3",
                },
                {
                  "Turkish Lira",
                  "TRY",
                  "949",
                  "2",
                },
                {
                  "Turkmenistan New Manat",
                  "TMT",
                  "934",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Australian Dollar",
                  "AUD",
                  "036",
                  "2",
                },
                {
                  "Uganda Shilling",
                  "UGX",
                  "800",
                  "0",
                },
                {
                  "Hryvnia",
                  "UAH",
                  "980",
                  "2",
                },
                {
                  "UAE Dirham",
                  "AED",
                  "784",
                  "2",
                },
                {
                  "Pound Sterling",
                  "GBP",
                  "826",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "Peso Uruguayo",
                  "UYU",
                  "858",
                  "2",
                },
                {
                  "Uzbekistan Sum",
                  "UZS",
                  "860",
                  "2",
                },
                {
                  "Vatu",
                  "VUV",
                  "548",
                  "0",
                },
                {
                  "Bolívar",
                  "VEF",
                  "937",
                  "2",
                },
                {
                  "Dong",
                  "VND",
                  "704",
                  "0",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "US Dollar",
                  "USD",
                  "840",
                  "2",
                },
                {
                  "CFP Franc",
                  "XPF",
                  "953",
                  "0",
                },
                {
                  "Moroccan Dirham",
                  "MAD",
                  "504",
                  "2",
                },
                {
                  "Yemeni Rial",
                  "YER",
                  "886",
                  "2",
                },
                {
                  "Zambian Kwacha",
                  "ZMW",
                  "967",
                  "2",
                },
                {
                  "Zimbabwe Dollar",
                  "ZWL",
                  "932",
                  "2",
                },
                {
                  "Bond Markets Unit European Composite Unit (EURCO)",
                  "XBA",
                  "955",
                  "N.A.",
                },
                {
                  "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
                  "XBB",
                  "956",
                  "N.A.",
                },
                {
                  "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
                  "XBC",
                  "957",
                  "N.A.",
                },
                {
                  "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
                  "XBD",
                  "958",
                  "N.A.",
                },
                {
                  "Codes specifically reserved for testing purposes",
                  "XTS",
                  "963",
                  "N.A.",
                },
                {
                  "The codes assigned for transactions where no currency is involved",
                  "XXX",
                  "999",
                  "N.A.",
                },
                {
                  "Gold",
                  "XAU",
                  "959",
                  "N.A.",
                },
                {
                  "Palladium",
                  "XPD",
                  "964",
                  "N.A.",
                },
                {
                  "Platinum",
                  "XPT",
                  "962",
                  "N.A.",
                },
                {
                  "Silver",
                  "XAG",
                  "961",
                  "N.A.",
                },
            };

            var currencies = this.Session.Create(this.Meta.ObjectType, data.Length);
            for (var i = 0; i < data.Length; i++)
            {
                var currency = (Currency)currencies[i];
                currency.Name = data[i, 0];
                currency.IsoCode = data[i, 1];

                // TODO: Number
                // TODO: Units
            }
        }

        protected override void BaseSecure(Security config)
        {
            var full = new[] { Operations.Read, Operations.Write, Operations.Execute };
            config.GrantAdministrator(this.ObjectType, full);
        }
    }
}