import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import 'rxjs/add/observable/combineLatest';
import { MetaDomain, SalesOrder, Good, SalesOrderItem, QuoteItem, VatRate, VatRegime, InventoryItem, SerialisedInventoryItem, NonSerialisedInventoryItem, SalesInvoiceItemType, Product } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class SalesOrderItemEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    order: SalesOrder;
    orderItem: SalesOrderItem;
    quoteItem: QuoteItem;
    goods: Good[];
    vatRates: VatRate[];
    vatRegimes: VatRegime[];
    discount: number;
    surcharge: number;
    inventoryItems: InventoryItem[];
    serialisedInventoryItem: SerialisedInventoryItem;
    nonSerialisedInventoryItem: NonSerialisedInventoryItem;
    salesInvoiceItemTypes: SalesInvoiceItemType[];
    productItemType: SalesInvoiceItemType;
    goodsFilter: Filter;
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    goodSelected(product: Product): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
