import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import 'rxjs/add/observable/combineLatest';
import { MetaDomain, Singleton, Person, ContactMechanism, Party, LetterCorrespondence, CommunicationEventPurpose } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class PartyCommunicationEventLetterCorrespondenceComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    subTitle: string;
    addSender: boolean;
    addReceiver: boolean;
    addAddress: boolean;
    m: MetaDomain;
    singleton: Singleton;
    communicationEvent: LetterCorrespondence;
    employees: Person[];
    contacts: Party[];
    party: Party;
    purposes: CommunicationEventPurpose[];
    postalAddresses: ContactMechanism[];
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    readonly PartyIsOrganisation: boolean;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    senderCancelled(): void;
    receiverCancelled(): void;
    addressCancelled(): void;
    senderAdded(id: string): void;
    receiverAdded(id: string): void;
    addressAdded(id: string): void;
    cancel(): void;
    close(): void;
    reopen(): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
