import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { ContactMechanism, MetaDomain, RequestForQuote, Person, Organisation, Currency, Party } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class RequestEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    request: RequestForQuote;
    people: Person[];
    organisations: Organisation[];
    currencies: Currency[];
    contactMechanisms: ContactMechanism[];
    contacts: Person[];
    addEmailAddress: boolean;
    addPostalAddress: boolean;
    addTeleCommunicationsNumber: boolean;
    addWebAddress: boolean;
    addPerson: boolean;
    peopleFilter: Filter;
    organisationsFilter: Filter;
    currenciesFilter: Filter;
    private refresh$;
    private subscription;
    private scope;
    private previousOriginator;
    readonly showOrganisations: boolean;
    readonly showPeople: boolean;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    submit(): void;
    cancel(): void;
    hold(): void;
    reject(): void;
    personCancelled(): void;
    personAdded(id: string): void;
    webAddressCancelled(): void;
    webAddressAdded(id: string): void;
    emailAddressCancelled(): void;
    emailAddressAdded(id: string): void;
    postalAddressCancelled(): void;
    postalAddressAdded(id: string): void;
    teleCommunicationsNumberCancelled(): void;
    teleCommunicationsNumberAdded(id: string): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    save(): void;
    originatorSelected(party: Party): void;
    refresh(): void;
    goBack(): void;
}
