import { AfterViewInit, ChangeDetectorRef, OnDestroy } from "@angular/core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { Title } from "@angular/platform-browser";
import { Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { Request } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class RequestsOverviewComponent implements AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private formBuilder;
    private titleService;
    private router;
    dialogService: TdDialogService;
    media: TdMediaService;
    private changeDetectorRef;
    total: number;
    searchForm: FormGroup;
    title: string;
    data: Request[];
    filtered: Request[];
    private refresh$;
    private page$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, formBuilder: FormBuilder, titleService: Title, router: Router, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    more(): void;
    goBack(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onView(request: Request): void;
}
