import { ids } from '@allors/meta/generated';

import {
  BasepriceEditComponent,
  CarrierEditComponent,
  CatalogueEditComponent,
  CustomerRelationshipEditComponent,
  CustomerShipmentCreateComponent,
  DisbursementEditComponent,
  OrderAdjustmentEditComponent,
  ProductIdentificationEditComponent,
  EmailAddressCreateComponent,
  EmailCommunicationEditComponent,
  EmploymentEditComponent,
  FaceToFaceCommunicationEditComponent,
  SalesTermEditComponent,
  InventoryItemTransactionEditComponent,
  LetterCorrespondenceEditComponent,
  OrganisationCreateComponent,
  OrganisationContactRelationshipEditComponent,
  NonSerialisedInventoryItemEditComponent,
  NonUnifiedGoodCreateComponent,
  NonUnifiedPartCreateComponent,
  PartyContactmechanismEditComponent,
  PartyRateEditComponent,
  PersonCreateComponent,
  PhoneCommunicationEditComponent,
  PositionTypeEditComponent,
  PositionTypeRateEditComponent,
  PostalAddressCreateComponent,
  ProductCategoryEditComponent,
  ProductQuoteCreateComponent,
  ProductTypeEditComponent,
  PurchaseInvoiceCreateComponent,
  PurchaseInvoiceItemEditComponent,
  PurchaseOrderCreateComponent,
  PurchaseOrderItemEditComponent,
  PurchaseReturnCreateComponent,
  PurchaseShipmentCreateComponent,
  QuoteItemEditComponent,
  ReceiptEditComponent,
  RepeatingPurchaseInvoiceEditComponent,
  RepeatingSalesInvoiceEditComponent,
  RequestItemEditComponent,
  RequestForQuoteCreateComponent,
  SalesInvoiceCreateComponent,
  SalesInvoiceItemEditComponent,
  SalesOrderCreateComponent,
  SalesOrderItemEditComponent,
  SerialisedItemCreateComponent,
  SerialisedItemCharacteristicEditComponent,
  ShipmentItemEditComponent,
  SubContractorRelationshipEditComponent,
  SupplierOfferingEditComponent,
  SupplierRelationshipEditComponent,
  TelecommunicationsNumberCreateComponent,
  TimeEntryEditComponent,
  UnifiedGoodCreateComponent,
  WebAddressCreateComponent,
  WorkEffortAssignmentRateEditComponent,
  WorkEffortFixedAssetAssignmentEditComponent,
  WorkEffortInventoryAssignmentEditComponent,
  WorkEffortPartyAssignmentEditComponent,
  WorkTaskCreateComponent,
  EmailAddressEditComponent,
  PostalAddressEditComponent,
  ProductQuoteApprovalEditComponent,
  PurchaseInvoiceApprovalEditComponent,
  PurchaseOrderApprovalLevel1EditComponent,
  PurchaseOrderApprovalLevel2EditComponent,
  TelecommunicationsNumberEditComponent,
  UserProfileEditComponent,
  WebAddressEditComponent,
} from '@allors/angular/material/module';

export const create = {
  [ids.BasePrice]: BasepriceEditComponent,
  [ids.Carrier]: CarrierEditComponent,
  [ids.Catalogue]: CatalogueEditComponent,
  [ids.CustomerRelationship]: CustomerRelationshipEditComponent,
  [ids.CustomerShipment]: CustomerShipmentCreateComponent,
  [ids.Disbursement]: DisbursementEditComponent,
  [ids.DiscountAdjustment]: OrderAdjustmentEditComponent,
  [ids.EanIdentification]: ProductIdentificationEditComponent,
  [ids.EmailAddress]: EmailAddressCreateComponent,
  [ids.EmailCommunication]: EmailCommunicationEditComponent,
  [ids.Employment]: EmploymentEditComponent,
  [ids.FaceToFaceCommunication]: FaceToFaceCommunicationEditComponent,
  [ids.Fee]: OrderAdjustmentEditComponent,
  [ids.IncoTerm]: SalesTermEditComponent,
  [ids.InventoryItemTransaction]: InventoryItemTransactionEditComponent,
  [ids.InvoiceTerm]: SalesTermEditComponent,
  [ids.IsbnIdentification]: ProductIdentificationEditComponent,
  [ids.LetterCorrespondence]: LetterCorrespondenceEditComponent,
  [ids.ManufacturerIdentification]: ProductIdentificationEditComponent,
  [ids.MiscellaneousCharge]: OrderAdjustmentEditComponent,
  [ids.OrderTerm]: SalesTermEditComponent,
  [ids.Organisation]: OrganisationCreateComponent,
  [ids.OrganisationContactRelationship]: OrganisationContactRelationshipEditComponent,
  [ids.NonSerialisedInventoryItem]: NonSerialisedInventoryItemEditComponent,
  [ids.NonUnifiedGood]: NonUnifiedGoodCreateComponent,
  [ids.NonUnifiedPart]: NonUnifiedPartCreateComponent,
  [ids.PartNumber]: ProductIdentificationEditComponent,
  [ids.PartyContactMechanism]: PartyContactmechanismEditComponent,
  [ids.PartyRate]: PartyRateEditComponent,
  [ids.Person]: PersonCreateComponent,
  [ids.PhoneCommunication]: PhoneCommunicationEditComponent,
  [ids.PositionType]: PositionTypeEditComponent,
  [ids.PositionTypeRate]: PositionTypeRateEditComponent,
  [ids.PostalAddress]: PostalAddressCreateComponent,
  [ids.ProductCategory]: ProductCategoryEditComponent,
  [ids.ProductNumber]: ProductIdentificationEditComponent,
  [ids.ProductQuote]: ProductQuoteCreateComponent,
  [ids.ProductType]: ProductTypeEditComponent,
  [ids.PurchaseInvoice]: PurchaseInvoiceCreateComponent,
  [ids.PurchaseInvoiceItem]: PurchaseInvoiceItemEditComponent,
  [ids.PurchaseOrder]: PurchaseOrderCreateComponent,
  [ids.PurchaseOrderItem]: PurchaseOrderItemEditComponent,
  [ids.PurchaseReturn]: PurchaseReturnCreateComponent,
  [ids.PurchaseShipment]: PurchaseShipmentCreateComponent,
  [ids.QuoteItem]: QuoteItemEditComponent,
  [ids.Receipt]: ReceiptEditComponent,
  [ids.RepeatingPurchaseInvoice]: RepeatingPurchaseInvoiceEditComponent,
  [ids.RepeatingSalesInvoice]: RepeatingSalesInvoiceEditComponent,
  [ids.RequestItem]: RequestItemEditComponent,
  [ids.RequestForQuote]: RequestForQuoteCreateComponent,
  [ids.SalesInvoice]: SalesInvoiceCreateComponent,
  [ids.SalesInvoiceItem]: SalesInvoiceItemEditComponent,
  [ids.SalesOrder]: SalesOrderCreateComponent,
  [ids.SalesOrderItem]: SalesOrderItemEditComponent,
  [ids.SerialisedItem]: SerialisedItemCreateComponent,
  [ids.SerialisedItemCharacteristicType]: SerialisedItemCharacteristicEditComponent,
  [ids.ShipmentItem]: ShipmentItemEditComponent,
  [ids.ShippingAndHandlingCharge]: OrderAdjustmentEditComponent,
  [ids.SkuIdentification]: ProductIdentificationEditComponent,
  [ids.SubContractorRelationship]: SubContractorRelationshipEditComponent,
  [ids.SupplierOffering]: SupplierOfferingEditComponent,
  [ids.SupplierRelationship]: SupplierRelationshipEditComponent,
  [ids.SurchargeAdjustment]: OrderAdjustmentEditComponent,
  [ids.TelecommunicationsNumber]: TelecommunicationsNumberCreateComponent,
  [ids.TimeEntry]: TimeEntryEditComponent,
  [ids.UnifiedGood]: UnifiedGoodCreateComponent,
  [ids.UpcaIdentification]: ProductIdentificationEditComponent,
  [ids.UpceIdentification]: ProductIdentificationEditComponent,
  [ids.WebAddress]: WebAddressCreateComponent,
  [ids.WorkEffortAssignmentRate]: WorkEffortAssignmentRateEditComponent,
  [ids.WorkEffortFixedAssetAssignment]: WorkEffortFixedAssetAssignmentEditComponent,
  [ids.WorkEffortInventoryAssignment]: WorkEffortInventoryAssignmentEditComponent,
  [ids.WorkEffortPartyAssignment]: WorkEffortPartyAssignmentEditComponent,
  // [ids.WorkEffortPurchaseOrderItemAssignment]: WorkEffortPurchaseOrderItemAssignmentEditComponent,
  [ids.WorkTask]: WorkTaskCreateComponent,
};

export const edit = {
  [ids.BasePrice]: BasepriceEditComponent,
  [ids.Carrier]: CarrierEditComponent,
  [ids.Catalogue]: CatalogueEditComponent,
  [ids.CustomerRelationship]: CustomerRelationshipEditComponent,
  [ids.Disbursement]: DisbursementEditComponent,
  [ids.DiscountAdjustment]: OrderAdjustmentEditComponent,
  [ids.EanIdentification]: ProductIdentificationEditComponent,
  [ids.EmailAddress]: EmailAddressEditComponent,
  [ids.EmailCommunication]: EmailCommunicationEditComponent,
  [ids.Employment]: EmploymentEditComponent,
  [ids.FaceToFaceCommunication]: FaceToFaceCommunicationEditComponent,
  [ids.Fee]: OrderAdjustmentEditComponent,
  [ids.IncoTerm]: SalesTermEditComponent,
  [ids.InventoryItemTransaction]: InventoryItemTransactionEditComponent,
  [ids.InvoiceTerm]: SalesTermEditComponent,
  [ids.IsbnIdentification]: ProductIdentificationEditComponent,
  [ids.LetterCorrespondence]: LetterCorrespondenceEditComponent,
  [ids.ManufacturerIdentification]: ProductIdentificationEditComponent,
  [ids.MiscellaneousCharge]: OrderAdjustmentEditComponent,
  [ids.NonSerialisedInventoryItem]: NonSerialisedInventoryItemEditComponent,
  [ids.OrderTerm]: SalesTermEditComponent,
  [ids.OrganisationContactRelationship]: OrganisationContactRelationshipEditComponent,
  [ids.PartyContactMechanism]: PartyContactmechanismEditComponent,
  [ids.PartyRate]: PartyRateEditComponent,
  [ids.PhoneCommunication]: PhoneCommunicationEditComponent,
  [ids.PositionType]: PositionTypeEditComponent,
  [ids.PositionTypeRate]: PositionTypeRateEditComponent,
  [ids.PostalAddress]: PostalAddressEditComponent,
  [ids.ProductCategory]: ProductCategoryEditComponent,
  [ids.PartNumber]: ProductIdentificationEditComponent,
  [ids.ProductNumber]: ProductIdentificationEditComponent,
  [ids.ProductType]: ProductTypeEditComponent,
  [ids.ProductQuoteApproval]: ProductQuoteApprovalEditComponent,
  [ids.PurchaseInvoiceApproval]: PurchaseInvoiceApprovalEditComponent,
  [ids.PurchaseInvoiceItem]: PurchaseInvoiceItemEditComponent,
  [ids.PurchaseOrderApprovalLevel1]: PurchaseOrderApprovalLevel1EditComponent,
  [ids.PurchaseOrderApprovalLevel2]: PurchaseOrderApprovalLevel2EditComponent,
  [ids.PurchaseOrderItem]: PurchaseOrderItemEditComponent,
  [ids.QuoteItem]: QuoteItemEditComponent,
  [ids.Receipt]: ReceiptEditComponent,
  [ids.RepeatingPurchaseInvoice]: RepeatingPurchaseInvoiceEditComponent,
  [ids.RepeatingSalesInvoice]: RepeatingSalesInvoiceEditComponent,
  [ids.RequestItem]: RequestItemEditComponent,
  [ids.SalesInvoiceItem]: SalesInvoiceItemEditComponent,
  [ids.SalesOrderItem]: SalesOrderItemEditComponent,
  [ids.SerialisedItemCharacteristicType]: SerialisedItemCharacteristicEditComponent,
  [ids.ShipmentItem]: ShipmentItemEditComponent,
  [ids.ShippingAndHandlingCharge]: OrderAdjustmentEditComponent,
  [ids.SkuIdentification]: ProductIdentificationEditComponent,
  [ids.SupplierOffering]: SupplierOfferingEditComponent,
  [ids.SubContractorRelationship]: SubContractorRelationshipEditComponent,
  [ids.SupplierRelationship]: SupplierRelationshipEditComponent,
  [ids.SurchargeAdjustment]: OrderAdjustmentEditComponent,
  [ids.TelecommunicationsNumber]: TelecommunicationsNumberEditComponent,
  [ids.TimeEntry]: TimeEntryEditComponent,
  [ids.UpcaIdentification]: ProductIdentificationEditComponent,
  [ids.UpceIdentification]: ProductIdentificationEditComponent,
  [ids.UserProfile]: UserProfileEditComponent,
  [ids.WebAddress]: WebAddressEditComponent,
  [ids.WorkEffortAssignmentRate]: WorkEffortAssignmentRateEditComponent,
  [ids.WorkEffortFixedAssetAssignment]: WorkEffortFixedAssetAssignmentEditComponent,
  [ids.WorkEffortInventoryAssignment]: WorkEffortInventoryAssignmentEditComponent,
  // [ids.WorkEffortPurchaseOrderItemAssignment]: WorkEffortPurchaseOrderItemAssignmentEditComponent,
  [ids.WorkEffortPartyAssignment]: WorkEffortPartyAssignmentEditComponent,
};
