export * from "./overview.module";
export * from "./dashboard/dashboard.module";
export * from "./person/person-overview.module";
export * from "./person/person.module";
export * from "./person/people-export.module";
export * from "./person/people-overview.module";
export * from "./organisation/organisations-overview.module";
export * from "./organisation/organisation-overview.module";
export * from "./organisation/organisation.module";
export * from "./organisation/contactrelationship/organisation-contactrelationship-add.module";
export * from "./organisation/contactrelationship/organisation-contactrelationship-edit.module";
export * from "./party/contactmechanism/emailaddress/party-contactmechanism-emailaddress-add.module";
export * from "./party/contactmechanism/emailaddress/party-contactmechanism-emailaddress-edit.module";
export * from "./party/contactmechanism/postaladdress/party-contactmechanism-postaladdress-add.module";
export * from "./party/contactmechanism/postaladdress/party-contactmechanism-postaladdress-edit.module";
export * from "./party/contactmechanism/telecommunicationsnumber/party-contactmechanism-telecommunicationsnumber-add.module";
export * from "./party/contactmechanism/telecommunicationsnumber/party-contactmechanism-telecommunicationsnumber-edit.module";
export * from "./party/contactmechanism/webaddress/party-contactmechanism-webaddress-add.module";
export * from "./party/contactmechanism/webaddress/party-contactmechanism-webaddress-edit.module";
export * from "./party/communicationevent/emailcommunication/party-communicationevent-emailcommunication.module";
export * from "./party/communicationevent/facetofacecommunication/party-communicationevent-facetofacecommunication.module";
export * from "./party/communicationevent/lettercorrespondence/party-communicationevent-lettercorrespondence.module";
export * from "./party/communicationevent/phonecommunication/party-communicationevent-phonecommunication.module";
export * from "./party/communicationevent/worktask/party-communicationevent-worktask.module";
export * from "./communicationevent/communicationevent-overview.module";
export * from "./communicationevent/communicationevents-overview.module";
import { OverviewModule } from "./overview.module";
export declare const Modules: (typeof OverviewModule)[];
