import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { MetaDomain, SalesOrder, Person, Organisation, ContactMechanism, ProductQuote, Currency, Party, VatRegime, VatRate, Store } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class SalesOrderEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    order: SalesOrder;
    quote: ProductQuote;
    people: Person[];
    organisations: Organisation[];
    currencies: Currency[];
    billToContactMechanisms: ContactMechanism[];
    ShipToAddresses: ContactMechanism[];
    vatRates: VatRate[];
    vatRegimes: VatRegime[];
    contacts: Person[];
    stores: Store[];
    addEmailAddress: boolean;
    addPostalAddress: boolean;
    addTeleCommunicationsNumber: boolean;
    addWebAddress: boolean;
    addShipToAddress: boolean;
    addPerson: boolean;
    peopleFilter: Filter;
    organisationsFilter: Filter;
    currenciesFilter: Filter;
    private refresh$;
    private subscription;
    private scope;
    private previousShipToCustomer;
    private previousBillToCustomer;
    readonly showOrganisations: boolean;
    readonly showPeople: boolean;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    personCancelled(): void;
    personAdded(id: string): void;
    webAddressCancelled(): void;
    webAddressAdded(id: string): void;
    emailAddressCancelled(): void;
    emailAddressAdded(id: string): void;
    postalAddressCancelled(): void;
    postalAddressAdded(id: string): void;
    teleCommunicationsNumberCancelled(): void;
    teleCommunicationsNumberAdded(id: string): void;
    shipToAddressCancelled(): void;
    shipToAddressAdded(id: string): void;
    approve(): void;
    cancel(): void;
    reject(): void;
    hold(): void;
    continue(): void;
    confirm(): void;
    finish(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    save(): void;
    shipToCustomerSelected(party: Party): void;
    billToCustomerSelected(party: Party): void;
    refresh(): void;
    goBack(): void;
}
