import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { MetaDomain, SalesInvoice, SalesOrder, Currency, ContactMechanism, VatRate, VatRegime, Party } from "@allors/workspace";
import { Organisation, Person } from "@allors/workspace";
import { Filter, WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class InvoiceComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    invoice: SalesInvoice;
    order: SalesOrder;
    people: Person[];
    organisations: Organisation[];
    currencies: Currency[];
    contactMechanisms: ContactMechanism[];
    vatRates: VatRate[];
    vatRegimes: VatRegime[];
    contacts: Person[];
    peopleFilter: Filter;
    organisationsFilter: Filter;
    currenciesFilter: Filter;
    addEmailAddress: boolean;
    addPostalAddress: boolean;
    addTeleCommunicationsNumber: boolean;
    addWebAddress: boolean;
    addPerson: boolean;
    private refresh$;
    private subscription;
    private scope;
    private previousBillToCustomer;
    readonly showOrganisations: boolean;
    readonly showPeople: boolean;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    personCancelled(): void;
    personAdded(id: string): void;
    webAddressCancelled(): void;
    webAddressAdded(id: string): void;
    emailAddressCancelled(): void;
    emailAddressAdded(id: string): void;
    postalAddressCancelled(): void;
    postalAddressAdded(id: string): void;
    teleCommunicationsNumberCancelled(): void;
    teleCommunicationsNumberAdded(id: string): void;
    send(): void;
    cancel(): void;
    writeOff(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    save(): void;
    receiverSelected(party: Party): void;
    refresh(): void;
    goBack(): void;
}
