// <auto-generated />
// Do not edit this file, changes will be overwritten.
namespace Allors.Domain
{
	public partial class CustomerShipmentPick
    {
        public bool Overridden { get; set; }
	}
}
