import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import 'rxjs/add/observable/combineLatest';
import { MetaDomain, Singleton, Person, ContactMechanism, Party, PhoneCommunication, CommunicationEventPurpose } from "@allors/workspace";
import { WorkspaceService, ErrorService } from "@allors/base-angular";
export declare class PartyCommunicationEventPhoneCommunicationComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    title: string;
    subTitle: string;
    addCaller: boolean;
    addReceiver: boolean;
    addPhoneNumber: boolean;
    m: MetaDomain;
    singleton: Singleton;
    communicationEvent: PhoneCommunication;
    employees: Person[];
    contacts: Party[];
    party: Party;
    purposes: CommunicationEventPurpose[];
    phonenumbers: ContactMechanism[];
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    readonly PartyIsOrganisation: boolean;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    phoneNumberCancelled(): void;
    callerCancelled(): void;
    receiverCancelled(): void;
    phoneNumberAdded(id: string): void;
    callerAdded(id: string): void;
    receiverAdded(id: string): void;
    cancel(): void;
    close(): void;
    reopen(): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
