import { AfterViewInit, ChangeDetectorRef, OnDestroy, OnInit } from "@angular/core";
import { MatSnackBar } from "@angular/material";
import { ActivatedRoute, Router } from "@angular/router";
import { TdDialogService, TdMediaService } from "@covalent/core";
import { MetaDomain, Good, RequestForQuote, RequestItem, InventoryItem, SerialisedInventoryItem, NonSerialisedInventoryItem, UnitOfMeasure, Product } from "@allors/workspace";
import { WorkspaceService, ErrorService, Filter } from "@allors/base-angular";
export declare class RequestItemEditComponent implements OnInit, AfterViewInit, OnDestroy {
    private workspaceService;
    private errorService;
    private router;
    private route;
    private snackBar;
    private dialogService;
    media: TdMediaService;
    private changeDetectorRef;
    m: MetaDomain;
    title: string;
    subTitle: string;
    request: RequestForQuote;
    requestItem: RequestItem;
    goods: Good[];
    inventoryItems: InventoryItem[];
    serialisedInventoryItem: SerialisedInventoryItem;
    nonSerialisedInventoryItem: NonSerialisedInventoryItem;
    unitsOfMeasure: UnitOfMeasure[];
    goodsFilter: Filter;
    private refresh$;
    private subscription;
    private scope;
    constructor(workspaceService: WorkspaceService, errorService: ErrorService, router: Router, route: ActivatedRoute, snackBar: MatSnackBar, dialogService: TdDialogService, media: TdMediaService, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    goodSelected(product: Product): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    submit(): void;
    cancel(): void;
    hold(): void;
    save(): void;
    refresh(): void;
    goBack(): void;
}
