export * from "./overview.module";
export * from "./order/orders-overview.module";
export * from "./productquote/productquote-overview.module";
export * from "./productquote/productquotes-overview.module";
export * from "./productquote/productquote-print.module";
export * from "./request/request-overview.module";
export * from "./request/requests-overview.module";
export * from "./salesorder/salesorder-overview.module";
export * from "./salesorder/salesorders-overview.module";
export * from "./salesorder/salesorder-print.module";
export * from "./productquote/productquote.module";
export * from "./quoteitem/quoteitem.module";
export * from "./request/request.module";
export * from "./requestitem/requestitem.module";
export * from "./salesorder/salesorder.module";
export * from "./salesorderitem/salesorderitem.module";
import { OverviewModule } from "./overview.module";
export declare const Modules: (typeof OverviewModule)[];
