name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install Nuke.Build
      run: dotnet tool install Nuke.GlobalTool --global
    - name: Build with PowerShell & Nuke
      run: |
            chmod +x build.sh
            ./build.sh
      shell: bash
