//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountNumber must be unique within Chart of accounts.
        /// </summary>
        public static string AccountNumberUniqueWithinChartOfAccounts {
            get {
                return ResourceManager.GetString("AccountNumberUniqueWithinChartOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active deployment registered at {0}.
        /// </summary>
        public static string ActiveDeploymentRegistered {
            get {
                return ResourceManager.GetString("ActiveDeploymentRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order quantity break not allowed for a base price.
        /// </summary>
        public static string BasePriceOrderQuantityBreakNotAllowed {
            get {
                return ResourceManager.GetString("BasePriceOrderQuantityBreakNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order value break not allowed for a base price.
        /// </summary>
        public static string BasePriceOrderValueNotAllowed {
            get {
                return ResourceManager.GetString("BasePriceOrderValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revenue quantity break not allowed for a base price.
        /// </summary>
        public static string BasePriceRevenueQuantityBreakNotAllowed {
            get {
                return ResourceManager.GetString("BasePriceRevenueQuantityBreakNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revenue value break not allowed for a base price.
        /// </summary>
        public static string BasePriceRevenueValueBreakNotAllowed {
            get {
                return ResourceManager.GetString("BasePriceRevenueValueBreakNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost center not in list of allowed cost centers.
        /// </summary>
        public static string CostCenterNotAllowed {
            get {
                return ResourceManager.GetString("CostCenterNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost unit not in list of allowed cost units.
        /// </summary>
        public static string CostUnitNotAllowed {
            get {
                return ResourceManager.GetString("CostUnitNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date does not match weekday.
        /// </summary>
        public static string DateDayOfWeek {
            get {
                return ResourceManager.GetString("DateDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is before start date.
        /// </summary>
        public static string EndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("EndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected frequency is not supported.
        /// </summary>
        public static string FrequencyNotSupported {
            get {
                return ResourceManager.GetString("FrequencyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger Account must be balance sheet account.
        /// </summary>
        public static string GeneralLedgerAccountNotBalanceAccount {
            get {
                return ResourceManager.GetString("GeneralLedgerAccountNotBalanceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger Account not applicable.
        /// </summary>
        public static string GeneralLedgerAccountNotNeutral {
            get {
                return ResourceManager.GetString("GeneralLedgerAccountNotNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check digits of IBAN are wrong.
        /// </summary>
        public static string IbanCheckDigitsError {
            get {
                return ResourceManager.GetString("IbanCheckDigitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IBAN contains illegal characters.
        /// </summary>
        public static string IbanIllegalCharacters {
            get {
                return ResourceManager.GetString("IbanIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IBAN is incorrect.
        /// </summary>
        public static string IbanIncorrect {
            get {
                return ResourceManager.GetString("IbanIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN length is wrong.
        /// </summary>
        public static string IbanLengthFailure {
            get {
                return ResourceManager.GetString("IbanLengthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country specific structure of IBAN is wrong.
        /// </summary>
        public static string IbanStructuralFailure {
            get {
                return ResourceManager.GetString("IbanStructuralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN validation rules for this country are not known.
        /// </summary>
        public static string IbanValidationUnavailable {
            get {
                return ResourceManager.GetString("IbanValidationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not a cost center account.
        /// </summary>
        public static string NotACostCenterAccount {
            get {
                return ResourceManager.GetString("NotACostCenterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not a cost unit account.
        /// </summary>
        public static string NotACostUnitAccount {
            get {
                return ResourceManager.GetString("NotACostUnitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid BIC code.
        /// </summary>
        public static string NotAValidBic {
            get {
                return ResourceManager.GetString("NotAValidBic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum package content.
        /// </summary>
        public static string PackagingContentMaximum {
            get {
                return ResourceManager.GetString("PackagingContentMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party choosen is not a customer for this internal organisation.
        /// </summary>
        public static string PartyIsNotACustomer {
            get {
                return ResourceManager.GetString("PartyIsNotACustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party choosen is not a supplier for this internal organisation.
        /// </summary>
        public static string PartyIsNotASupplier {
            get {
                return ResourceManager.GetString("PartyIsNotASupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount can not be larger then invoice amount.
        /// </summary>
        public static string PaymentApplicationNotLargerThanInvoiceAmount {
            get {
                return ResourceManager.GetString("PaymentApplicationNotLargerThanInvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount can not be larger then invoice item amount.
        /// </summary>
        public static string PaymentApplicationNotLargerThanInvoiceItemAmount {
            get {
                return ResourceManager.GetString("PaymentApplicationNotLargerThanInvoiceItemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount can not be larger then payment amount.
        /// </summary>
        public static string PaymentApplicationNotLargerThanPaymentAmount {
            get {
                return ResourceManager.GetString("PaymentApplicationNotLargerThanPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method not listed for owner of this store.
        /// </summary>
        public static string PaymentMethodNotAllowedForInternalOrganisation {
            get {
                return ResourceManager.GetString("PaymentMethodNotAllowedForInternalOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity more than allowed.
        /// </summary>
        public static string PickListItemQuantityMoreThanAllowed {
            get {
                return ResourceManager.GetString("PickListItemQuantityMoreThanAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package only allowed at lowest level.
        /// </summary>
        public static string ProductCategoryPackageOnlyAtLowestLevel {
            get {
                return ResourceManager.GetString("ProductCategoryPackageOnlyAtLowestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount is to small.
        /// </summary>
        public static string ReceiptAmountIsToSmall {
            get {
                return ResourceManager.GetString("ReceiptAmountIsToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity less than already shipped.
        /// </summary>
        public static string SalesOrderItemLessThanAlreadeyShipped {
            get {
                return ResourceManager.GetString("SalesOrderItemLessThanAlreadeyShipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product change not allowed, user cancel orderitem instead.
        /// </summary>
        public static string SalesOrderItemProductChangeNotAllowed {
            get {
                return ResourceManager.GetString("SalesOrderItemProductChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested quantity to ship immediately is larger than the quantity that is ordered.
        /// </summary>
        public static string SalesOrderItemQuantityToShipNowIsLargerThanQuantityOrdered {
            get {
                return ResourceManager.GetString("SalesOrderItemQuantityToShipNowIsLargerThanQuantityOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested quantity to ship immediately is larger than the quantity remaining to ship.
        /// </summary>
        public static string SalesOrderItemQuantityToShipNowIsLargerThanQuantityRemaining {
            get {
                return ResourceManager.GetString("SalesOrderItemQuantityToShipNowIsLargerThanQuantityRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested quantity to ship immediately is not available.
        /// </summary>
        public static string SalesOrderItemQuantityToShipNowNotAvailable {
            get {
                return ResourceManager.GetString("SalesOrderItemQuantityToShipNowNotAvailable", resourceCulture);
            }
        }
    }
}
